/*
types for action-reducer
*/

export const SELLERS_FETCH_BEGIN = 'SELLERS_FETCH_BEGIN';
export const SELLERS_FETCH_END = 'SELLERS_FETCH_END';
export const SELLERS_FETCH_ERROR = 'SELLERS_FETCH_ERROR';

export const SELLER_SELECT = 'SELLER_SELECT';

export const SELLER_FEATURED_FETCH_END = 'SELLER_FEATURED_FETCH_END';
export const SELLER_CATEGORIES_FETCH_END = 'SELLER_CATEGORIES_FETCH_END';

export const LOAD_BASKETS = 'LOAD_BASKETS';
export const RECHECK_PRICES = 'RECHECK_PRICES';

export const BASKET_INIT = 'BASKET_INIT';
export const BASKET_ITEM_INCR = 'BASKET_ITEM_INCR';
export const BASKET_ITEM_DECR = 'BASKET_ITEM_DECR';
export const BASKET_ITEMS_CLEAR = 'BASKET_ITEMS_CLEAR';
export const BASKET_ITEM_SPECIAL_REQ = 'BASKET_ITEM_SPECIAL_REQ';

export const COUPON_CODE_RESET = 'COUPON_CODE_RESET';
export const COUPON_CODE_SUCCESS = 'COUPON_CODE_SUCCESS';
export const COUPON_CODE_FAILURE = 'COUPON_CODE_FAILURE';
export const COUPON_CODE_LOADING = 'COUPON_CODE_LOADING';

export const CUSTOMER_DATA_SET = 'CUSTOMER_DATA_SET';
export const CUSTOMER_DATA_LISTENER_SET = 'CUSTOMER_DATA_LISTENER_SET';
export const CUSTOMER_DATA_RESET = 'CUSTOMER_DATA_RESET';

export const LOCALE_SET = 'LOCALE_SET';
export const DEVICEID_SET = 'DEVICEID_SET';

export const ADDRESSES_SET = 'ADDRESSES_SET';
export const ADDRESSES_LISTENER_SET = 'ADDRESSES_LISTENER_SET';

export const TIMESLOT_SET = 'TIMESLOT_SET';
export const TIP_SET = 'TIP_SET';
export const ORDER_NOTES_SET = 'ORDER_NOTES_SET';


/* Credit Card Creation */
export const PAYMENT_METHOD_SET = 'PAYMENT_METHOD_SET';

export const CREDITCARD_CREATE_BEGIN = 'CREDITCARD_CREATE_BEGIN';
export const CREDITCARD_CREATE_SUCCESS = 'CREDITCARD_CREATE_SUCCESS';
export const CREDITCARD_CREATE_FAIL = 'CREDITCARD_CREATE_FAIL';
export const CREDITCARD_CREATE_RESET = 'CREDITCARD_CREATE_RESET';

export const CREDITCARDS_SET = 'CREDITCARDS_SET';
export const CREDITCARDS_LISTENER_SET = 'CREDITCARDS_LISTENER_SET';

/* Address Creation */
export const ADDRESS_CREATE_RESET = 'ADDRESS_CREATE_RESET';
export const ADDRESS_DETAIL_SET = 'ADDRESS_DETAIL_SET';

// for getting coord details from google places
export const ADDRESS_LOCATION_BEGIN = 'ADDRESS_LOCATION_BEGIN';
export const ADDRESS_LOCATION_SET = 'ADDRESS_LOCATION_SET';
export const ADDRESS_LOCATION_ERROR = 'ADDRESS_LOCATION_ERROR';

export const ADDRESS_AREA_BEGIN = 'ADDRESS_AREA_BEGIN';
export const ADDRESS_AREA_SET = 'ADDRESS_AREA_SET';
export const ADDRESS_AREA_ERROR = 'ADDRESS_AREA_ERROR';

export const CURRENT_LOCATION_BEGIN = 'CURRENT_LOCATION_BEGIN';
export const CURRENT_LOCATION_ERROR = 'CURRENT_LOCATION_ERROR';

export const ADDRESS_SEARCH_RESET = 'ADDRESS_SEARCH_RESET';
export const ADDRESS_SEARCH_BEGIN = 'ADDRESS_SEARCH_BEGIN';
export const ADDRESS_SEARCH_SET = 'ADDRESS_SEARCH_SET';

export const LOCATION_REVERSE_SEARCH_BEGIN = 'LOCATION_REVERSE_SEARCH_BEGIN'; // get street from pin
export const LOCATION_REVERSE_SEARCH_SET = 'LOCATION_REVERSE_SEARCH_SET';

export const ADDRESS_SUBMIT_BEGIN = 'ADDRESS_SUBMIT_BEGIN';
export const ADDRESS_SUBMIT_SUCCESS = 'ADDRESS_SUBMIT_SUCCESS';
export const ADDRESS_SUBMIT_ERROR = 'ADDRESS_SUBMIT_ERROR';

export const ADDRESS_SELECT_BEGIN = 'ADDRESS_SELECT_BEGIN';
export const ADDRESS_SELECT_SUCCESS = 'ADDRESS_SELECT_SUCCESS';
export const ADDRESS_SELECT_ERROR = 'ADDRESS_SELECT_ERROR';

export const AUTH_PHONE_SET = 'AUTH_PHONE_SET';
export const AUTH_COUNTRY_CODE_SET = 'AUTH_COUNTRY_CODE_SET';
export const AUTH_VERIFICATION_SET = 'AUTH_VERIFICATION_SET';
export const AUTH_INIT = 'AUTH_INIT';

export const GUEST_LOGIN_BEGIN = 'GUEST_LOGIN_BEGIN';
export const GUEST_LOGIN_SUCCESS = 'GUEST_LOGIN_SUCCESS';
export const GUEST_LOGIN_FAIL = 'GUEST_LOGIN_FAIL';


export const PHONE_ENTRY_BEGIN = 'PHONE_ENTRY_BEGIN';
export const PHONE_ENTRY_SUCCESS = 'PHONE_ENTRY_SUCCESS';
export const PHONE_ENTRY_FAIL = 'PHONE_ENTRY_FAIL';

export const VERIFICATION_BEGIN = 'VERIFICATION_BEGIN';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';

export const TIMESLOTS_FETCH_BEGIN = 'TIMESLOTS_FETCH_BEGIN';
export const TIMESLOTS_FETCH_SET = 'TIMESLOTS_FETCH_SET';
export const TIMESLOTS_FETCH_ERROR = 'TIMESLOTS_FETCH_ERROR';

export const CHECKOUT_RESET = 'CHECKOUT_RESET';

export const ORDER_SUBMIT_BEGIN = 'ORDER_SUBMIT_BEGIN';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAIL = 'ORDER_SUBMIT_FAIL';

export const ORDER_HISTORY_FETCH_BEGIN = 'ORDER_HISTORY_FETCH_BEGIN';
export const ORDER_HISTORY_FETCH_SET = 'ORDER_HISTORY_FETCH_SET';

export const ORDER_TRACK_LISTENER_SET = 'ORDER_TRACK_LISTENER_SET';
export const ORDER_TRACK_DATA_SET = 'ORDER_TRACK_DATA_SET';
export const ORDER_ITEMS_TRACK_DATA_SET = 'ORDER_ITEMS_TRACK_DATA_SET';
export const ORDER_TRACK_LISTENER_RESET = 'ORDER_TRACK_LISTENER_RESET';

export const REVIEW_ITEMS_DATA_BEGIN = 'REVIEW_ITEMS_DATA_BEGIN';
export const REVIEW_ITEMS_DATA_SET = 'REVIEW_ITEMS_DATA_SET';
export const REVIEW_SUBSTITUTION_SET = 'REVIEW_SUBSTITUTION_SET';


export const DRIVER_TRACK_LISTENER_SET = 'DRIVER_TRACK_LISTENER_SET';
export const DRIVER_TRACK_DATA_SET = 'DRIVER_TRACK_DATA_SET';
export const DRIVER_TRACK_LISTENER_RESET = 'DRIVER_TRACK_LISTENER_RESET';

export const ONGOING_ORDERS_SET = 'ONGOING_ORDERS_SET';
export const ONGOING_ORDERS_LISTENER_SET = 'ONGOING_ORDERS_LISTENER_SET';
export const REVIEW_ORDER_SET = 'REVIEW_ORDER_SET';
export const FEEDBACK_ORDER_SET = 'FEEDBACK_ORDER_SET';
export const ONGOING_ORDERS_RESET = 'ONGOING_ORDERS_RESET';


export const FEEDBACK_RESET = 'FEEDBACK_RESET';
export const FEEDBACK_STORE_RATING_SET = 'FEEDBACK_STORE_RATING_SET';
export const FEEDBACK_AYEZ_RATING_SET = 'FEEDBACK_AYEZ_RATING_SET';
export const FEEDBACK_SELLER_SET = 'FEEDBACK_SELLER_SET';

export const FEEDBACK_SUBMIT_BEGIN = 'FEEDBACK_SUBMIT_BEGIN';
export const FEEDBACK_SUBMIT_SUCCESS = 'FEEDBACK_SUBMIT_SUCCESS';
export const FEEDBACK_SUBMIT_ERROR = 'FEEDBACK_SUBMIT_ERROR';


export const SEARCH_SUBCATEGORY_DATA_BEGIN = 'SEARCH_SUBCATEGORY_DATA_BEGIN';
export const SEARCH_SUBCATEGORY_DATA_END = 'SEARCH_SUBCATEGORY_DATA_END';

export const SUPPORT_MANUAL_SET = 'SUPPORT_MANUAL_SET';
