/*
types for action-reducer
*/

export const SELLERS_FETCH_BEGIN = 'SELLERS_FETCH_BEGIN';
export const SELLERS_FETCH_END = 'SELLERS_FETCH_END';
export const SELLERS_FETCH_ERROR = 'SELLERS_FETCH_ERROR';

export const SELLER_SELECT = 'SELLER_SELECT';


export const REGIONS_FETCH_BEGIN = 'REGIONS_FETCH_BEGIN';
export const REGIONS_FETCH_SET = 'REGIONS_FETCH_SET';
export const AREA_RESULTS_FETCH_BEGIN = 'AREA_RESULTS_FETCH_BEGIN';
export const AREA_RESULTS_FETCH_SET = 'AREA_RESULTS_FETCH_SET';


export const SELECTED_AREA_SET = 'SELECTED_AREA_SET';
export const SAVED_AREAS_SET = 'SAVED_AREAS_SET';
export const SAVED_AREAS_BEGIN = 'SAVED_AREAS_BEGIN';
export const SAVED_AREAS_FAIL = 'SAVED_AREAS_FAIL';

export const SELLER_FEATURED_FETCH_END = 'SELLER_FEATURED_FETCH_END';
export const SELLER_CATEGORIES_FETCH_END = 'SELLER_CATEGORIES_FETCH_END';

export const LOAD_BASKETS = 'LOAD_BASKETS';
export const RECHECK_PRICES = 'RECHECK_PRICES';

export const BASKET_INIT = 'BASKET_INIT';
export const BASKET_ITEM_INCR = 'BASKET_ITEM_INCR';
export const BASKET_ITEM_DECR = 'BASKET_ITEM_DECR';
export const BASKET_ITEMS_CLEAR = 'BASKET_ITEMS_CLEAR';
export const BASKET_ITEM_SPECIAL_REQ = 'BASKET_ITEM_SPECIAL_REQ';

export const COUPON_CODE_RESET = 'COUPON_CODE_RESET';
export const COUPON_CODE_SUCCESS = 'COUPON_CODE_SUCCESS';
export const COUPON_CODE_FAILURE = 'COUPON_CODE_FAILURE';
export const COUPON_CODE_LOADING = 'COUPON_CODE_LOADING';

export const CUSTOMER_DATA_SET = 'CUSTOMER_DATA_SET';
export const CUSTOMER_DATA_LISTENER_SET = 'CUSTOMER_DATA_LISTENER_SET';
export const CUSTOMER_DATA_RESET = 'CUSTOMER_DATA_RESET';

export const LOCALE_SET = 'LOCALE_SET';
export const DEVICEID_SET = 'DEVICEID_SET';

export const ADDRESSES_SET = 'ADDRESSES_SET';
export const ADDRESSES_LISTENER_SET = 'ADDRESSES_LISTENER_SET';

export const TIMESLOT_SET = 'TIMESLOT_SET';
export const TIP_SET = 'TIP_SET';
export const ORDER_NOTES_SET = 'ORDER_NOTES_SET';

/* Credit Card Creation */
export const PAYMENT_METHOD_SET = 'PAYMENT_METHOD_SET';

export const CREDITCARD_CREATE_BEGIN = 'CREDITCARD_CREATE_BEGIN';
export const CREDITCARD_CREATE_SUCCESS = 'CREDITCARD_CREATE_SUCCESS';
export const CREDITCARD_CREATE_FAIL = 'CREDITCARD_CREATE_FAIL';
export const CREDITCARD_CREATE_RESET = 'CREDITCARD_CREATE_RESET';

export const CREDITCARDS_SET = 'CREDITCARDS_SET';
export const CREDITCARDS_LISTENER_SET = 'CREDITCARDS_LISTENER_SET';

/* Address Creation */
export const ADDRESS_CREATE_RESET = 'ADDRESS_CREATE_RESET';
export const ADDRESS_DETAIL_SET = 'ADDRESS_DETAIL_SET';

// for getting coord details from google places
export const ADDRESS_LOCATION_BEGIN = 'ADDRESS_LOCATION_BEGIN';
export const ADDRESS_LOCATION_SET = 'ADDRESS_LOCATION_SET';
export const ADDRESS_LOCATION_ERROR = 'ADDRESS_LOCATION_ERROR';

export const CURRENT_AREA_BEGIN = 'CURRENT_AREA_BEGIN';
export const CURRENT_AREA_SET = 'CURRENT_AREA_SET';
export const CURRENT_AREA_ERROR = 'CURRENT_AREA_ERROR';

export const CURRENT_LOCATION_BEGIN = 'CURRENT_LOCATION_BEGIN';
export const CURRENT_LOCATION_ERROR = 'CURRENT_LOCATION_ERROR';

export const ADDRESS_SEARCH_RESET = 'ADDRESS_SEARCH_RESET';
export const ADDRESS_SEARCH_BEGIN = 'ADDRESS_SEARCH_BEGIN';
export const ADDRESS_SEARCH_SET = 'ADDRESS_SEARCH_SET';

export const LOCATION_REVERSE_SEARCH_BEGIN = 'LOCATION_REVERSE_SEARCH_BEGIN'; // get street from pin
export const LOCATION_REVERSE_SEARCH_SET = 'LOCATION_REVERSE_SEARCH_SET';

export const ADDRESS_SUBMIT_BEGIN = 'ADDRESS_SUBMIT_BEGIN';
export const ADDRESS_SUBMIT_SUCCESS = 'ADDRESS_SUBMIT_SUCCESS';
export const ADDRESS_SUBMIT_ERROR = 'ADDRESS_SUBMIT_ERROR';

export const ADDRESS_SELECT_BEGIN = 'ADDRESS_SELECT_BEGIN';
export const ADDRESS_SELECT_SUCCESS = 'ADDRESS_SELECT_SUCCESS';
export const ADDRESS_SELECT_ERROR = 'ADDRESS_SELECT_ERROR';

export const ADDRESS_UPDATE_BEGIN = 'ADDRESS_UPDATE_BEGIN';
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS';
export const ADDRESS_UPDATE_ERROR = 'ADDRESS_UPDATE_ERROR';

export const AUTH_PHONE_SET = 'AUTH_PHONE_SET';
export const AUTH_COUNTRY_CODE_SET = 'AUTH_COUNTRY_CODE_SET';
export const AUTH_VERIFICATION_SET = 'AUTH_VERIFICATION_SET';
export const AUTH_INIT = 'AUTH_INIT';

export const GUEST_LOGIN_BEGIN = 'GUEST_LOGIN_BEGIN';
export const GUEST_LOGIN_SUCCESS = 'GUEST_LOGIN_SUCCESS';
export const GUEST_LOGIN_FAIL = 'GUEST_LOGIN_FAIL';


export const ROBOCALL_BEGIN = 'ROBOCALL_BEGIN';
export const ROBOCALL_SUCCESS = 'ROBOCALL_SUCCESS';
export const ROBOCALL_ERROR = 'ROBOCALL_ERROR';

export const PHONE_ENTRY_BEGIN = 'PHONE_ENTRY_BEGIN';
export const PHONE_ENTRY_SUCCESS = 'PHONE_ENTRY_SUCCESS';
export const PHONE_ENTRY_FAIL = 'PHONE_ENTRY_FAIL';

export const VERIFICATION_BEGIN = 'VERIFICATION_BEGIN';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';

export const TIMESLOTS_FETCH_BEGIN = 'TIMESLOTS_FETCH_BEGIN';
export const TIMESLOTS_FETCH_SET = 'TIMESLOTS_FETCH_SET';
export const TIMESLOTS_FETCH_ERROR = 'TIMESLOTS_FETCH_ERROR';

export const CHECKOUT_RESET = 'CHECKOUT_RESET';

export const ORDER_SUBMIT_BEGIN = 'ORDER_SUBMIT_BEGIN';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAIL = 'ORDER_SUBMIT_FAIL';

export const ORDER_HISTORY_FETCH_BEGIN = 'ORDER_HISTORY_FETCH_BEGIN';
export const ORDER_HISTORY_FETCH_SET = 'ORDER_HISTORY_FETCH_SET';

export const ORDER_TRACK_LISTENER_SET = 'ORDER_TRACK_LISTENER_SET';
export const ORDER_TRACK_DATA_SET = 'ORDER_TRACK_DATA_SET';
export const ORDER_ITEMS_TRACK_DATA_SET = 'ORDER_ITEMS_TRACK_DATA_SET';
export const ORDER_TRACK_LISTENER_RESET = 'ORDER_TRACK_LISTENER_RESET';

export const REVIEW_ITEMS_DATA_BEGIN = 'REVIEW_ITEMS_DATA_BEGIN';
export const REVIEW_ITEMS_DATA_SET = 'REVIEW_ITEMS_DATA_SET';
export const REVIEW_SUBSTITUTION_SET = 'REVIEW_SUBSTITUTION_SET';

export const DRIVER_TRACK_LISTENER_SET = 'DRIVER_TRACK_LISTENER_SET';
export const DRIVER_TRACK_DATA_SET = 'DRIVER_TRACK_DATA_SET';
export const DRIVER_TRACK_LISTENER_RESET = 'DRIVER_TRACK_LISTENER_RESET';

export const ONGOING_ORDERS_SET = 'ONGOING_ORDERS_SET';
export const ONGOING_ORDERS_LISTENER_SET = 'ONGOING_ORDERS_LISTENER_SET';
export const REVIEW_ORDER_SET = 'REVIEW_ORDER_SET';
export const FEEDBACK_ORDER_SET = 'FEEDBACK_ORDER_SET';
export const ONGOING_ORDERS_RESET = 'ONGOING_ORDERS_RESET';

export const FEEDBACK_RESET = 'FEEDBACK_RESET';
export const FEEDBACK_STORE_RATING_SET = 'FEEDBACK_STORE_RATING_SET';
export const FEEDBACK_AYEZ_RATING_SET = 'FEEDBACK_AYEZ_RATING_SET';
export const FEEDBACK_SELLER_SET = 'FEEDBACK_SELLER_SET';

export const FEEDBACK_SUBMIT_BEGIN = 'FEEDBACK_SUBMIT_BEGIN';
export const FEEDBACK_SUBMIT_SUCCESS = 'FEEDBACK_SUBMIT_SUCCESS';
export const FEEDBACK_SUBMIT_ERROR = 'FEEDBACK_SUBMIT_ERROR';

export const SEARCH_SUBCATEGORY_DATA_BEGIN = 'SEARCH_SUBCATEGORY_DATA_BEGIN';
export const SEARCH_SUBCATEGORY_DATA_END = 'SEARCH_SUBCATEGORY_DATA_END';

export const ITEM_BARCODE_SEARCH_BEGIN = 'ITEM_BARCODE_SEARCH_BEGIN';
export const ITEM_BARCODE_SEARCH_SUCCESS = 'ITEM_BARCODE_SEARCH_SUCCESS';
export const ITEM_BARCODE_SEARCH_ERROR = 'ITEM_BARCODE_SEARCH_ERROR';
export const ITEM_BARCODE_SEARCH_RESET = 'ITEM_BARCODE_SEARCH_RESET';

export const SUPPORT_MANUAL_SET = 'SUPPORT_MANUAL_SET';

export const SUPPORT_MESSAGES_SET = 'SUPPORT_MESSAGES_SET';
export const SUPPORT_MESSAGES_LISTENER_SET = 'SUPPORT_MESSAGES_LISTENER_SET';
export const CHAT_SET = 'CHAT_SET';
export const CHAT_LISTENER_SET = 'CHAT_LISTENER_SET';
export const MESSAGE_SEND_BEGIN = 'MESSAGE_SEND_BEGIN';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';

export const ADD_GENERAL_SUPPORT_MESSAGE = 'ADD_GENERAL_SUPPORT_MESSAGE';
export const ADD_SUPPORT_USER = 'ADD_SUPPORT_USER';
export const VALIDATE_SUPPORT_MESSAGE = 'VALIDATE_SUPPORT_MESSAGE';

/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */

// OLD TYPES from migration below
// they will be deleted, so if you are using any, place them above

/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */

/* Fetching all subcat data for a category */
export const CATEGORY_DATA_BEGIN = 'CATEGORY_DATA_BEGIN';
export const CATEGORY_DATA_SET = 'CATEGORY_DATA_SET';

export const SUBCATEGORY_SET = 'SUBCATEGORY_SET';

export const SET_BASKETS = 'SET_BASKETS';
export const SET_SELLER_BASKET = 'SET_SELLER_BASKET';

export const CHECK_IF_PROMO_SET = 'CHECK_IF_PROMO_SET';
export const CHECK_IF_RECENT_SET = 'CHECK_IF_RECENT_SET';

export const SET_CUSTOM_ITEM_MODAL = 'SET_CUSTOM_ITEM_MODAL';
export const HIDE_CUSTOM_ITEM_MODAL = 'HIDE_CUSTOM_ITEM_MODAL';

export const SHOW_STORE_MODAL = 'SHOW_STORE_MODAL';
export const HIDE_STORE_MODAL = 'HIDE_STORE_MODAL';

export const CREATE_CUSTOMER_DATA_ATTEMPT = 'CREATE_CUSTOMER_DATA_ATTEMPT';
export const CREATE_CUSTOMER_DATA_SUCCESS = 'CREATE_CUSTOMER_DATA_SUCCESS';
export const CREATE_CUSTOMER_DATA_FAIL = 'CREATE_CUSTOMER_DATA_FAIL';

export const ITEM_SEARCH_QUERY_SET = 'ITEM_SEARCH_QUERY_SET';
export const ITEM_SEARCH_CATEGORY_SET = 'ITEM_SEARCH_CATEGORY_SET';
export const ITEM_SEARCH_DATA_SET = 'ITEM_SEARCH_DATA_SET';
export const ITEM_SEARCH_DATA_RESET = 'ITEM_SEARCH_DATA_RESET';

export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const SET_PRIOR_STACK = 'SET_PRIOR_STACK';

export const PAYMENT_METHOD_BEGIN = 'PAYMENT_METHOD_BEGIN';
export const PAYMENT_METHOD_FAIL = 'PAYMENT_METHOD_FAIL';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_ATTEMPT_SUCCESS = 'LOGIN_ATTEMPT_SUCCESS';
export const LOGIN_ATTEMPT_FAIL = 'LOGIN_ATTEMPT_FAIL';
export const LOGIN_ATTEMPT_RESET = 'LOGIN_ATTEMPT_RESET';

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT';
export const LOGOUT_ATTEMPT_SUCCESS = 'LOGOUT_ATTEMPT_SUCCESS';
export const LOGOUT_ATTEMPT_FAIL = 'LOGOUT_ATTEMPT_FAIL';

export const VERIFICATION_ENTERED = 'VERIFICATION_ENTERED';

export const CUSTOMER_POINTS_SET = 'CUSTOMER_POINTS_SET';
export const CUSTOMER_POINTS_LISTENER_SET = 'CUSTOMER_POINTS_LISTENER_SET';

export const TOGGLE_COUPON_MODAL = 'TOGGLE_COUPON_MODAL';

export const ACTIVE_ORDERS_SET = 'ACTIVE_ORDERS_SET';
export const ACTIVE_ORDERS_LISTENER_SET = 'ACTIVE_ORDERS_LISTENER_SET';
export const LAST_ORDER_SET = 'LAST_ORDER_SET';
export const SUBSTITUTION_ORDER_SET = 'SUBSTITUTION_ORDER_SET';

export const ORDER_HISTORY_SET = 'ORDER_HISTORY_SET';
export const ORDER_HISTORY_LISTENER_SET = 'ORDER_HISTORY_LISTENER_SET';
export const ORDER_HISTORY_LISTENER_RESET = 'ORDER_HISTORY_LISTENER_RESET';

export const CURRENT_SELLER_BEGIN = 'CURRENT_SELLER_BEGIN';
export const CURRENT_SELLER_SELECT = 'CURRENT_SELLER_SELECT';
export const CURRENT_SELLER_RESET = 'CURRENT_SELLER_RESET';
export const CURRENT_SELLER_DETAILS = 'CURRENT_SELLER_DETAILS';
export const CURRENT_SELLER_LAYOUT = 'CURRENT_SELLER_LAYOUT';

export const SUBSTITUTION_SUBMIT_BEGIN = 'SUBSTITUTION_SUBMIT_BEGIN';
export const SUBSTITUTION_SUBMIT_END = 'SUBSTITUTION_SUBMIT_END';

export const SUBSTITUTION_OPTIONS_BEGIN = 'SUBSTITUTION_OPTIONS_BEGIN';
export const SUBSTITUTION_OPTIONS_SET = 'SUBSTITUTION_OPTIONS_SET';

export const SELLER_SEARCH_BEGIN = 'SELLER_SEARCH_BEGIN';
export const SELLER_SEARCH_SET = 'SELLER_SEARCH_SET';

export const ORDER_ITEM_ADD = 'ORDER_ITEM_ADD';
export const ORDER_ITEM_REMOVE = 'ORDER_ITEM_REMOVE';

export const SELECT_SELLER_LOAD = 'SELECT_SELLER_LOAD';

export const AUTH_SELLER_SELECT = 'AUTH_SELLER_SELECT';
