//  Created by react-native-create-bridge

import { NativeModules } from 'react-native'

const { WeAccept } = NativeModules

export default {
  start (params) {
    return WeAccept.start(params)
  },
  FIRST_NAME: WeAccept.FIRST_NAME,
  LAST_NAME: WeAccept.LAST_NAME,
  BUILDING: WeAccept.BUILDING,
  FLOOR: WeAccept.FLOOR,
  APARTMENT: WeAccept.APARTMENT,
  CITY: WeAccept.CITY,
  STATE: WeAccept.STATE,
  COUNTRY: WeAccept.COUNTRY,
  EMAIL: WeAccept.EMAIL,
  PHONE_NUMBER: WeAccept.PHONE_NUMBER,
  POSTAL_CODE: WeAccept.POSTAL_CODE,
  PAYMENT_KEY: WeAccept.PAYMENT_KEY,
  THREE_D_SECURE_ACTIVITY_TITLE: WeAccept.THREE_D_SECURE_ACTIVITY_TITLE,
  SAVE_CARD_DEFAULT: WeAccept.SAVE_CARD_DEFAULT,
  SHOW_ALERTS: WeAccept.SHOW_ALERTS,
  SHOW_SAVE_CARD: WeAccept.SHOW_SAVE_CARD,
  THEME_COLOR: WeAccept.THEME_COLOR,
  TOKEN: WeAccept.TOKEN,
  MASKED_PAN_NUMBER: WeAccept.MASKED_PAN_NUMBER,
  USER_CANCELED: WeAccept.USER_CANCELED,
  MISSING_ARGUMENT: WeAccept.MISSING_ARGUMENT,
  TRANSACTION_ERROR: WeAccept.TRANSACTION_ERROR,
  TRANSACTION_REJECTED: WeAccept.TRANSACTION_REJECTED,
  TRANSACTION_REJECTED_PARSING_ISSUE: WeAccept.TRANSACTION_REJECTED_PARSING_ISSUE,
  TRANSACTION_SUCCESSFUL: WeAccept.TRANSACTION_SUCCESSFUL,
  TRANSACTION_SUCCESSFUL_PARSING_ISSUE: WeAccept.TRANSACTION_SUCCESSFUL_PARSING_ISSUE,
  TRANSACTION_SUCCESSFUL_CARD_SAVED: WeAccept.TRANSACTION_SUCCESSFUL_CARD_SAVED,
  USER_CANCELED_3D_SECURE_VERIFICATION: WeAccept.USER_CANCELED_3D_SECURE_VERIFICATION,
  USER_CANCELED_3D_SECURE_VERIFICATION_PARSING_ISSUE: WeAccept.USER_CANCELED_3D_SECURE_VERIFICATION_PARSING_ISSUE,
  MISSING_ARGUMENT_VALUE: WeAccept.MISSING_ARGUMENT_VALUE,
  RESPONSE_DATA_MESSAGE: WeAccept.RESPONSE_DATA_MESSAGE,
  TRANSACTION_ERROR_REASON: WeAccept.TRANSACTION_ERROR_REASON,
  RAW_PAY_RESPONSE: WeAccept.RAW_PAY_RESPONSE,
  RESPONSE_TOKEN: WeAccept.RESPONSE_TOKEN,
  PENDING: WeAccept.PENDING
}
