# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build("5.8.2", 1)
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  def build(version_number, build_number)
    match
    set_version(version_number, build_number)
    build_app(workspace: "ayezcustomer.xcworkspace", scheme: "ayezcustomer")
  end

  def set_version(version_number, build_number)
    new_version_number = increment_version_number(
			version_number: version_number
		)
		build_number = increment_build_number(
		  build_number: build_number
		)
  end
  
end
