# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_require 'dotenv'

default_platform(:ios)

before_all do |lane, options|
  Dotenv.load('../../.env')
  ensure_git_branch(branch: ENV['GIT_BRANCH'])
end

platform :ios do


  desc "Push a new beta build to TestFlight"
  lane :beta do
       build
       upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  private_lane :build do |options|
     match
     update_version
     gym
  end

  private_lane :update_version do |options|
    version_number =  increment_version_number_in_plist(version_source: 'appstore', bump_type:'patch', scheme:'ayezcustomer')  
    build_number = latest_testflight_build_number(version: version_number) + 1
  	increment_build_number_in_plist(build_number:build_number.to_s, scheme:'ayezcustomer')
  end
  
end
