# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_require 'dotenv'

default_platform(:ios)

before_all do |lane, options|
  Dotenv.load('../../.env')
  ensure_git_branch
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
      app_version = build(bump_type:options[:version_type], scheme:ENV["SCHEME"])
      upload_to_testflight
      commit_version_bump(message: "Version #{app_version[:version_number]} build #{app_version[:build_number]}", xcodeproj: "ayezcustomer.xcodeproj")
      add_git_tag(tag: "v-#{app_version[:version_number]}b-#{app_version[:build_number]}")
      download_dsyms(version: app_version[:version_number], build_number: app_version[:build_number])
      sentry_upload_dsym
  end

  private_lane :build do |options|
     match
     app_version = update_version(bump_type:options[:bump_type], scheme:options[:scheme]) 
     gym
     app_version
  end

  private_lane :update_version do |options|
    version_number =  increment_version_number_in_plist(version_source: 'appstore', bump_type:options[:bump_type], scheme:options[:scheme])  
    build_number = latest_testflight_build_number(version: version_number) + 1   
    increment_build_number_in_plist(build_number:build_number.to_s, scheme:options[:scheme]) 
    {version_number: version_number, build_number: build_number.to_s}
  end
  
end
